version: "3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./database/db:/data/db
      - ./database/config:/data/configdb
  employee:
    image: ghcr.io/hannah-ellis-opencast-software/test-api:latest
    expose:
      - 5001
    ports:
      - 5001:8080
    restart: always
    depends_on:
      - db
volumes:
  data:
  config:
